#!/usr/bin/env node
/**
 * Vendors IBM Plex into the module and generates its @font-face SCSS.
 *
 * Odoo serves /<module>/static/** directly, so the woff2 files just live in
 * static/fonts/ with no controller. Three Odoo-specific transforms are applied
 * to @ibm/plex-*'s own split CSS:
 *
 *   1. URLs are rewritten ABSOLUTE. StylesheetAsset.rx_url rewrites relative
 *      url(...) to be relative to the asset's web directory; its negative
 *      lookahead exempts anything starting with "/", so an absolute URL passes
 *      through untouched and survives the file moving between bundles.
 *   2. font-display: swap is added -- the split CSS ships without it.
 *   3. local() is dropped. It makes the browser prefer whatever Plex the user
 *      happens to have installed, which may be a different version with
 *      different metrics. Carbon's own font CSS drops it too, and it keeps the
 *      emitted bytes deterministic, which --check depends on.
 *
 * Only the faces the theme actually asks for are vendored. Carbon caps
 * emphasis at SemiBold, and the bridge sets $o-font-weight-bold: 600, so no
 * Bold (700) face is shipped -- nothing would ever request it.
 *
 *   node tools/gen-fonts.mjs           write
 *   node tools/gen-fonts.mjs --check   compare only, exit 1 if stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const OUT_FONTS = path.join(ROOT, "static/fonts");
const URL_BASE = "/web_theme_carbon/static/fonts";

// unicode-range keeps these cheap: a Latin-1 session downloads only Latin1.
const SUBSETS = ["Latin1", "Latin2", "Latin3", "Cyrillic", "Greek", "Pi"];
const FACES = [
  ["@ibm/plex-sans", "IBMPlexSans-Light"],
  ["@ibm/plex-sans", "IBMPlexSans-Regular"],
  ["@ibm/plex-sans", "IBMPlexSans-Italic"],
  ["@ibm/plex-sans", "IBMPlexSans-SemiBold"],
  ["@ibm/plex-mono", "IBMPlexMono-Regular"],
  ["@ibm/plex-mono", "IBMPlexMono-SemiBold"],
];

let stale = false;
const copied = [];
const blocks = [];

for (const [pkg, face] of FACES) {
  const dir = path.join(ROOT, "node_modules", pkg, "fonts/split/woff2");
  const cssPath = path.join(dir, `${face}.css`);
  if (!fs.existsSync(cssPath)) {
    console.error(`  MISSING ${pkg}/${face}.css`);
    process.exitCode = 1;
    continue;
  }
  let css = fs.readFileSync(cssPath, "utf8");

  // keep only the subsets we ship
  css = css
    .split(/(?=\/\* Subset:)/)
    .filter((b) => SUBSETS.some((s) => b.includes(`Subset: ${s}`)))
    .join("");

  for (const s of SUBSETS) {
    const f = `${face}-${s}.woff2`;
    const src = path.join(dir, f);
    if (fs.existsSync(src)) copied.push([src, f]);
  }

  css = css
    .replace(/local\("[^"]*"\),\s*/g, "")
    .replace(/url\("([^"]+)"\)/g, `url("${URL_BASE}/$1")`)
    .replace(/(font-weight:\s*\d+;?)/g, "$1\n\tfont-display: swap;")
    .replace(/\t/g, "    ");
  blocks.push(css.trim());
}

// -- copy the binaries -------------------------------------------------------
if (!CHECK) fs.mkdirSync(OUT_FONTS, { recursive: true });
for (const [src, name] of copied) {
  const dst = path.join(OUT_FONTS, name);
  const buf = fs.readFileSync(src);
  const same = fs.existsSync(dst) && Buffer.compare(fs.readFileSync(dst), buf) === 0;
  if (same) continue;
  if (CHECK) { stale = true; console.error(`  STATIC static/fonts/${name}`); continue; }
  fs.writeFileSync(dst, buf);
}

// -- emit the SCSS -----------------------------------------------------------
const scss = [
  "// GENERATED by tools/gen-fonts.mjs -- DO NOT EDIT.",
  "// Run `npm run codegen` in this module instead.",
  "//",
  "// IBM Plex, self-hosted from static/fonts/. URLs are absolute so Odoo's",
  "// StylesheetAsset url-rewriting leaves them alone. No Bold (700) face:",
  "// Carbon caps emphasis at SemiBold and the bridge sets",
  "// $o-font-weight-bold: 600, so nothing would ever request one.",
  "//",
  "// IBM Plex is licensed OFL-1.1; see static/fonts/LICENSE-plex-*.txt.",
  "",
  ...blocks,
  "",
].join("\n");

const scssPath = path.join(ROOT, "static/src/scss/generated/_carbon_fonts.scss");
const prev = fs.existsSync(scssPath) ? fs.readFileSync(scssPath, "utf8") : null;
if (prev === scss) {
  console.log("  ok    static/src/scss/generated/_carbon_fonts.scss");
} else if (CHECK) {
  stale = true;
  console.error("  STALE static/src/scss/generated/_carbon_fonts.scss");
} else {
  fs.writeFileSync(scssPath, scss);
  console.log(`  write static/src/scss/generated/_carbon_fonts.scss (${scss.length} bytes)`);
}

// -- licences travel with the binaries ---------------------------------------
for (const pkg of ["@ibm/plex-sans", "@ibm/plex-mono"]) {
  const src = path.join(ROOT, "node_modules", pkg, "LICENSE.txt");
  if (!fs.existsSync(src)) continue;
  const dst = path.join(OUT_FONTS, `LICENSE-${pkg.split("/")[1]}.txt`);
  if (!CHECK) fs.copyFileSync(src, dst);
}

console.log(`  fonts: ${copied.length} woff2 across ${FACES.length} faces`);
if (stale) {
  console.error("\nGenerated font assets are out of date. Run `npm run codegen`.");
  process.exit(1);
}
