# Copyright 2026 Avunu LLC
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
"""Re-express web_company_color's palette as Carbon design tokens.

web_company_color compiles a hardcoded SCSS template per company, stores the
result as an ir.attachment, and injects it into ``web.webclient_bootstrap``
*after* every other bundle -- with ``!important`` on nearly every declaration.
Left alone it does not merely tint the Carbon theme, it overwrites it: navbar,
buttons, links, search facets, the statusbar and the stat buttons all revert to
its own Odoo-flavoured palette.

So this module replaces the template rather than fighting it. The company's
colours are emitted as Carbon tokens, which the theme's component CSS already
reads, so one colour propagates coherently to buttons, focus rings, selected
rows, the notebook underline, the side-nav rule and the rest -- instead of the
handful of places the stock template happens to name.

Two mechanisms make this possible without any !important of our own:

* everything the theme draws from ``var(--cds-*)`` follows from re-declaring
  those custom properties on ``:root``;
* buttons are compiled to literals by Odoo, but Bootstrap 5.3's
  ``button-variant()`` writes ``--btn-bg`` / ``--btn-hover-bg`` / ... and
  ``.btn`` reads them back (Odoo sets ``$variable-prefix`` to ''), so setting
  those custom properties makes Bootstrap's own rules serve our values.

The navbar is the one surface that genuinely needs plain declarations: the
theme compiles it from ``$o-navbar-*`` SCSS variables, which no runtime
property can reach.
"""

from colorsys import hls_to_rgb, rgb_to_hls

from odoo import models

from odoo.addons.web_company_color.utils import n_rgb_to_hex

# Carbon g10 defaults, mirrored from
# web_theme_carbon/static/src/scss/generated/_carbon_tokens.scss. They are
# repeated here because this template is compiled standalone by
# web_company_color -- none of the theme's SCSS is in scope -- and because a
# company that sets only one colour must still get a coherent Carbon palette
# for the rest.
CARBON = {
    "primary": "#0f62fe",  # interactive / button-primary (Blue 60)
    "primary_hover": "#0050e6",
    "primary_active": "#002d9c",
    "link": "#0f62fe",
    "link_hover": "#0043ce",
    "on_primary": "#ffffff",  # text-on-color
    "shell_bg": "#161616",  # the UI Shell header is g100 in every theme
    "shell_border": "#393939",
    "shell_text": "#f4f4f4",
}


def _parse_hex(value):
    """`#abc` / `#aabbcc` -> (r, g, b) floats, or None if it is not a hex colour.

    Company colours come from a `widget="color"` field, so they are normally
    well-formed -- but the field is a plain Char and nothing stops a value
    being set another way, and a malformed colour must degrade to "leave it
    alone" rather than raise during a res.company write.
    """
    if not isinstance(value, str):
        return None
    text = value.strip().lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    if len(text) != 6:
        return None
    try:
        return tuple(int(text[i : i + 2], 16) / 255 for i in (0, 2, 4))
    except ValueError:
        return None


def shade(value, amount):
    """Darken a hex colour by `amount` (0..1) of lightness.

    Computed in Python on purpose. The obvious alternative -- emitting
    `darken($c, 10%)` and letting libsass resolve it -- silently does not work
    here: Sass treats the value of a CUSTOM PROPERTY as plain CSS and does not
    evaluate functions inside it, so `--cds-button-primary-hover: darken(...)`
    reaches the browser as the literal text `darken(#8a3ffc, 8%)`, which is
    invalid and simply ignored. Every token this module emits is a custom
    property, so every shade has to be a literal before it gets there.
    """
    rgb = _parse_hex(value)
    if rgb is None:
        return value
    hue, lightness, saturation = rgb_to_hls(*rgb)
    red, green, blue = hls_to_rgb(hue, max(0.0, lightness - amount), saturation)
    return n_rgb_to_hex(red, green, blue)


class ResCompany(models.Model):
    _inherit = "res.company"

    def _get_scss_template(self):
        # NOTE: %(...)s placeholders -- this string is interpolated by
        # web_company_color with the dict from _scss_get_sanitized_values().
        return """
/* Generated by web_theme_carbon_company_color.
   web_company_color's palette, re-expressed as Carbon design tokens. */

:root {
    /* The interactive family. Everything the theme styles through
       var(--cds-*) follows from these: focus rings, selected rows, the
       notebook underline, the side-nav rule, the statusbar current step. */
    --cds-interactive: %(carbon_primary)s;
    --cds-border-interactive: %(carbon_primary)s;
    --cds-focus: %(carbon_primary)s;
    --cds-background-brand: %(carbon_primary)s;

    --cds-link-primary: %(carbon_link)s;
    --cds-link-primary-hover: %(carbon_link_hover)s;

    --cds-button-primary: %(carbon_primary)s;
    --cds-button-primary-hover: %(carbon_primary_hover)s;
    --cds-button-primary-active: %(carbon_primary_active)s;
    --cds-button-tertiary: %(carbon_primary)s;
}

/* Buttons are compiled to literals by Odoo's $o-btns-bs-override map, so the
   tokens above cannot reach them. Bootstrap's button-variant() writes --btn-*
   and .btn reads it back, so setting those properties is enough -- no
   !important, and no dependence on load order. */
.btn-primary {
    --btn-color: %(carbon_on_primary)s;
    --btn-bg: %(carbon_primary)s;
    --btn-border-color: %(carbon_primary)s;
    --btn-hover-color: %(carbon_on_primary)s;
    --btn-hover-bg: %(carbon_primary_hover)s;
    --btn-hover-border-color: %(carbon_primary_hover)s;
    --btn-active-color: %(carbon_on_primary)s;
    --btn-active-bg: %(carbon_primary_active)s;
    --btn-active-border-color: %(carbon_primary_active)s;
    --btn-disabled-color: %(carbon_on_primary)s;
    --btn-disabled-bg: %(carbon_primary)s;
    --btn-disabled-border-color: %(carbon_primary)s;
}

/* Carbon's tertiary button: transparent until hover, then it fills. */
.btn-outline-primary {
    --btn-color: %(carbon_primary)s;
    --btn-border-color: %(carbon_primary)s;
    --btn-hover-color: %(carbon_on_primary)s;
    --btn-hover-bg: %(carbon_primary_hover)s;
    --btn-hover-border-color: %(carbon_primary_hover)s;
    --btn-active-color: %(carbon_on_primary)s;
    --btn-active-bg: %(carbon_primary_active)s;
    --btn-active-border-color: %(carbon_primary_active)s;
}

/* The navbar is the one surface the theme compiles from SCSS variables
   ($o-navbar-*), which no custom property can reach -- hence real
   declarations. Kept to the three that matter; the theme still owns the
   spacing, the 48px height and the current-item rule. */
.o_main_navbar {
    background-color: %(carbon_shell_bg)s;
    border-bottom: 1px solid %(carbon_shell_border)s;
    color: %(carbon_shell_text)s;
}
"""

    def _scss_get_sanitized_values(self):
        """Map web_company_color's fields onto Carbon roles.

        Each field goes to its natural counterpart rather than to the one place
        its name mentions:

        * ``color_button_bg``  -> the whole Carbon *interactive* family. This is
          the field that answers "what is our primary colour", so it drives
          focus rings and selected states too, not just buttons.
        * ``color_link_text``  -> link-primary, falling back to the primary.
        * ``color_navbar_bg``  -> the UI Shell header.

        Anything unset falls back to Carbon's own g10 value, so a company that
        sets one colour still gets a coherent palette instead of a mix of its
        brand and Odoo purple.
        """
        self.ensure_one()
        values = dict(self.company_colors or {})

        primary = values.get("color_button_bg") or CARBON["primary"]
        link = values.get("color_link_text") or primary
        shell_bg = values.get("color_navbar_bg") or CARBON["shell_bg"]

        # Carbon's own hover/active steps are hand-tuned, so they are used
        # verbatim whenever the colour has not been changed; a custom brand
        # colour gets the same relative treatment computed from it.
        is_default_primary = primary == CARBON["primary"]
        is_default_link = link == CARBON["link"]
        is_default_shell = shell_bg == CARBON["shell_bg"]

        carbon = {
            "carbon_primary": primary,
            "carbon_primary_hover": (
                values.get("color_button_bg_hover")
                or (CARBON["primary_hover"] if is_default_primary else shade(primary, 0.06))
            ),
            "carbon_primary_active": (
                CARBON["primary_active"] if is_default_primary else shade(primary, 0.16)
            ),
            "carbon_on_primary": values.get("color_button_text") or CARBON["on_primary"],
            "carbon_link": link,
            "carbon_link_hover": (
                values.get("color_link_text_hover")
                or (CARBON["link_hover"] if is_default_link else shade(link, 0.10))
            ),
            "carbon_shell_bg": shell_bg,
            "carbon_shell_border": (
                values.get("color_navbar_border_bottom")
                or (CARBON["shell_border"] if is_default_shell else shade(shell_bg, 0.08))
            ),
            "carbon_shell_text": values.get("color_navbar_text") or CARBON["shell_text"],
        }

        # Keep the stock keys too: this dict is what feeds the template, and a
        # third module may still extend web_company_color's own.
        values.update(carbon)
        return values
